apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-containers
          image: jgarrels/capstone
          ports:
          - name: http
            containerPort: 80