apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-containers
          image: jgarrels/capstone:latest
          ports:
          - name: http
            containerPort: 80