apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-east-2

nodeGroups:
  - name: servers 
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: false